### ISSUE TITLE
coin3: add click_amount and format amount as $0.01

### ISSUE THREAD

**Issue by topshef** [topshef/animatedbuttons#10]
re
live https://kpay.live/scratchpad/animatedbuttons/mediumclap/coin3.html
repo https://github.com/topshef/animatedbuttons/blob/master/mediumclap/coin3.html

update coin3 (a copy of coin2) to apply the following changes to the green counter circle:

change +1 +2 etc to instead show $0.01 $0.02 etc with each click
set a constant for the click increment amount, eg click_amount = 0.05 would result in $0.05 $0.10 $0.15 etc

increase size of green circle if needed

make a copy of the css / js as needed so it does not affect coin2

**Comment by yunusbulutt** [comment]
I would like to solve this! Can you please assign?

**Comment by topshef** [comment]
@yunusbulutt thanks for your interest! I would have done, but someone already helped with a solution so this will now close. But there will be more if you are interested.
